using System;
using System.Windows.Forms;

namespace GolfMemberSys
{
    public partial class frmMemberTypeAnalysis : Form
    {
        public frmMemberTypeAnalysis()
        {
            InitializeComponent();
        }

        private void btnAnalysisDate_Click(object sender, EventArgs e)
        {

            //Take in selected dates as strings
            String date1 = dtpAnalysis1.Value.ToString("dd - MMM - y");
            String date2 = dtpAnalysis2.Value.ToString("dd - MMM - y");

            //Pass both dates to the method and use the returned dataset as the datagridview's data source to show the resulting renewals
            grdAnalysisDate.DataSource = Utility.getRenewalsByDate(date1, date2).Tables["RENEWALS"];
  
        }

        private void quitToolStripMenuItem_Click(object sender, EventArgs e)
        {
            if (MessageBox.Show("Are you sure you want to exit?", "Exit Application", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.No)
            {
                this.Show();
            }
            else
            {
                Application.Exit();
            }
        }

        private void backToolStripMenuItem_Click(object sender, EventArgs e)
        {
            frmMainMenu goBack = new frmMainMenu();
            this.Close();
            goBack.Show();
        }

        private void frmNewTypeAnalysis_Load(object sender, EventArgs e)
        {
            grdAnalysisType.DataSource = MemberTypes.getMemberTypes().Tables["MEMBERTYPES"];
        }

        private void grdAnalysisType_CellClick(object sender, DataGridViewCellEventArgs e)
        {

            //Fixes crashing when an empty row is clicked
            try
            {

                //Get typeID from selected row in the datagrid and assign it to typeID
                String typeID = grdAnalysisType.Rows[grdAnalysisType.CurrentCell.RowIndex].Cells[0].Value.ToString();

                //Create new MemberType object to call getTypeCount() with the typeID
                MemberTypes singleType = new MemberTypes();
                int typeCount = singleType.getTypeCount(typeID);

                //Display typeCount on the UI as a label.
                txtMemberCount.Text = typeCount.ToString();

                //Fill the second Datagrid with the members of the selected Membership Type.
                grdAnalysisMembers.DataSource = Members.getMembersFromType(typeID).Tables["GOLFMEMBERSLOG"];

                //Get the current revenue generated by the member type selected
                MemberTypes typeIncome = new MemberTypes();
                decimal income = typeIncome.getTypeRevenue(typeID);

                decimal currentRevenue = income * typeCount;

                txtIncome.Text = currentRevenue.ToString();

            } // end try

            catch (InvalidOperationException)
            {
                MessageBox.Show("Please select a non empty row");
            }

        }
    }
}
